import { Link, Navigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import ContactForm from '../components/ContactForm';
import MarketingLayout from '../components/MarketingLayout';
import Seo from '../components/Seo';

const capabilities=[['Plan','Create programmes, trainings, workshops and events with clear schedules, venues, facilitators and ownership.'],['Register','Use public registration links and reusable participant profiles instead of rebuilding lists for every activity.'],['Attend','Capture field attendance with secure check-in links built for phones and fast-moving event environments.'],['Assess','Run surveys and assessments connected to the activity so learning outcomes remain tied to delivery.'],['Certify','Issue completion, attendance and appreciation certificates with professional organisation details.'],['Report','Bring activity, participant and outcome data together for operational review and evidence.']];
const faq=[['Can I use LexAMS for free?','Yes. The Free plan supports up to 50 participants and is intended to be genuinely useful for small programmes. No card is required to create a workspace.'],['Who is LexAMS for?','LexAMS is designed for training providers, NGOs, development programmes, schools, institutions and internal learning teams.'],['What changes when I upgrade to Pro?','Pro expands participant, activity, team, survey, assessment and certificate capacity and adds collaboration, export, branding and timed assessments.'],['How are payments handled?','Payments for LexAMS Pro are handled securely. Monthly billing is GMD 1,000 and annual billing is GMD 10,000.'],['Can participants use LexAMS without accounts?','Yes. Registration, attendance, surveys and assessments can be completed through scoped public links without requiring participant accounts.']];
const schema={"@context":"https://schema.org","@type":"SoftwareApplication",name:"LexAMS",applicationCategory:"BusinessApplication",operatingSystem:"Web",url:"https://lexams.netlify.app",description:"Training and programme management software for activities, participants, attendance, assessments, surveys, certificates and reporting.",offers:[{"@type":"Offer",name:"Free",price:"0",priceCurrency:"GMD"},{"@type":"Offer",name:"Pro Monthly",price:"1000",priceCurrency:"GMD"},{"@type":"Offer",name:"Pro Annual",price:"10000",priceCurrency:"GMD"}],publisher:{"@type":"Organization",name:"LexoGraphix Plus",address:{"@type":"PostalAddress",addressLocality:"Banjul",addressCountry:"GM"}}};

export default function Landing(){const {user}=useAuth();if(user)return <Navigate to="/app" replace/>;return <MarketingLayout><Seo title="LexAMS | Training & Programme Management" description="Manage training activities, participants, attendance, assessments, surveys, certificates and reporting from one workspace." path="/" schema={schema}/>
<section className="mk-hero"><div className="mk-container mk-hero-grid"><div><div className="mk-kicker">Training & programme management</div><h1>Manage every activity from registration to results.</h1><p>LexAMS helps training providers, NGOs and institutions manage participants, attendance, assessments, surveys, certificates and reporting from one connected workspace.</p><div className="mk-hero-actions"><Link className="mk-btn gold" to="/signup">Start free</Link><Link className="mk-btn ghost" to="/features">Explore features</Link></div><p style={{fontSize:12,color:'#748194',marginTop:16}}>Up to 50 participants on Free · No card required</p></div><div className="mk-product"><img src="/assets/lexams-workflow-v2.svg" alt="LexAMS programme workflow interface illustration"/><div className="mk-metrics"><div className="mk-metric"><strong>1</strong><span>workspace</span></div><div className="mk-metric"><strong>6</strong><span>connected workflows</span></div><div className="mk-metric"><strong>50</strong><span>participants on Free</span></div></div></div></div></section>
<section className="mk-section"><div className="mk-container"><div className="mk-section-head"><div><div className="mk-kicker">Why LexAMS</div><h2>Replace scattered admin with one operational flow.</h2></div><p className="mk-lede">When programme data lives across spreadsheets, forms, WhatsApp threads and separate certificate files, every reporting cycle creates more reconciliation work. LexAMS keeps those records connected from the start.</p></div><div className="mk-grid3">{capabilities.map(([h,p],i)=><div className="mk-card" key={h}><div className="mk-kicker">0{i+1}</div><h3>{h}</h3><p>{p}</p></div>)}</div></div></section>
<section className="mk-section mk-alt"><div className="mk-container"><div className="mk-section-head"><div><div className="mk-kicker">Built for real programmes</div><h2>Different organisations. The same need for clean delivery records.</h2></div><p className="mk-lede">LexAMS is intentionally broad enough for recurring trainings, workshops, community programmes, professional development and institutional activities.</p></div><div className="mk-grid3"><div className="mk-card"><h3>Training providers</h3><p>Run cohorts, workshops and short courses with registration, attendance, assessment and certification connected.</p><Link to="/solutions/training-providers" style={{display:'inline-block',marginTop:14,fontWeight:800,color:'#0E4C8F'}}>See solution →</Link></div><div className="mk-card"><h3>NGOs & programmes</h3><p>Keep implementation records consistent across programme teams and make outcome evidence easier to prepare.</p><Link to="/solutions/ngos" style={{display:'inline-block',marginTop:14,fontWeight:800,color:'#0E4C8F'}}>See solution →</Link></div><div className="mk-card"><h3>Schools & institutions</h3><p>Coordinate workshops, professional development and non-classroom learning activities in one workspace.</p><Link to="/solutions/education" style={{display:'inline-block',marginTop:14,fontWeight:800,color:'#0E4C8F'}}>See solution →</Link></div></div></div></section>
<section className="mk-section"><div className="mk-container"><div className="mk-section-head"><div><div className="mk-kicker">Trust by design</div><h2>Start with facts we can stand behind.</h2></div><p className="mk-lede">LexAMS does not rely on invented customer counts or testimonials. The product trust story is the workflow itself: scoped workspaces, server-side public flows, secure sign-in links and verified billing callbacks.</p></div><div className="mk-grid3"><div className="mk-card"><h3>Secure workspace access</h3><p>Passwordless email-link authentication and organisation-scoped application requests.</p></div><div className="mk-card"><h3>Server-backed participant flows</h3><p>Public registration, check-in, surveys and assessments now reach Neon through controlled server endpoints instead of direct browser database access.</p></div><div className="mk-card"><h3>Local GMD billing</h3><p>Pro subscriptions are billed in Gambian dalasi with branded LexAMS invoices and receipts.</p></div></div></div></section>
<section className="mk-section mk-alt"><div className="mk-container"><div className="mk-section-head"><div><div className="mk-kicker">Pricing</div><h2>Useful before you pay.</h2></div><p className="mk-lede">The Free plan supports real small programmes. Upgrade when capacity, collaboration and professional outputs become important.</p></div><div className="mk-pricing"><div className="mk-price"><h2>Free</h2><div className="mk-price-num">GMD 0</div><ul className="mk-list"><li>Up to 50 participants</li><li>2 active activities</li><li>Surveys and assessments</li><li>5 certificates per month</li></ul><Link className="mk-btn ghost" to="/signup">Start free</Link></div><div className="mk-price pro"><div className="mk-kicker">Recommended</div><h2>Pro</h2><div className="mk-price-num">GMD 1,000 <small>/month</small></div><p className="mk-lede">GMD 10,000 annually · GMD 833/month.</p><ul className="mk-list"><li>Up to 5,000 participants</li><li>Up to 100 active activities</li><li>Up to 20 team seats with collaboration</li><li>Expanded surveys and assessments</li><li>Timed assessments and CSV export</li><li>Custom organisation branding</li><li>Up to 1,000 certificates per month</li></ul><Link className="mk-btn primary" to="/pricing">Compare plans</Link></div></div></div></section>
<section className="mk-section"><div className="mk-container"><div className="mk-section-head"><div><div className="mk-kicker">FAQ</div><h2>Questions before you start.</h2></div><p className="mk-lede">The essentials about Free, Pro, participants and billing.</p></div><div className="mk-faq">{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
<section className="mk-section mk-alt" id="contact"><div className="mk-container"><div className="mk-section-head"><div><div className="mk-kicker">Contact</div><h2>Need LexAMS for an institution or programme?</h2></div><p className="mk-lede">Send us a note about your organisation, programme size or billing question.</p></div><ContactForm/></div></section>
<section className="mk-cta"><div className="mk-container mk-cta-in"><h2>Start with your next activity.</h2><Link className="mk-btn gold" to="/signup">Create a free workspace</Link></div></section>
</MarketingLayout>}
