import { Link } from 'react-router-dom';

export default function AuthPageLayout({ eyebrow, title, description, children, footer }) {
  return <div className="authx"><style>{`
    .authx{min-height:100vh;display:grid;grid-template-columns:1.05fr .95fr;background:#FBFAF7;color:#122033;font-family:var(--font-body,Inter,sans-serif)}
    .authx-story{padding:56px;display:flex;flex-direction:column;justify-content:space-between;background:radial-gradient(circle at 75% 20%,rgba(250,183,45,.20),transparent 28%),linear-gradient(160deg,#002B54,#0A3A68);color:#fff}
    .authx-brand{font:700 26px var(--font-heading,Georgia,serif);color:#fff;text-decoration:none}.authx-kicker{font-size:11px;letter-spacing:.15em;text-transform:uppercase;font-weight:800;color:#FAB72D}.authx-story h2{font:700 clamp(38px,5vw,62px)/1.03 var(--font-heading,Georgia,serif);letter-spacing:-.035em;margin:12px 0 18px;max-width:620px}.authx-story p{max-width:560px;line-height:1.75;color:rgba(255,255,255,.76)}.authx-points{display:grid;gap:12px;margin-top:28px}.authx-point{display:flex;gap:10px;font-size:13px;color:rgba(255,255,255,.84)}.authx-point:before{content:'✓';color:#FAB72D;font-weight:900}.authx-meta{font-size:11px;color:rgba(255,255,255,.54)}
    .authx-main{display:flex;align-items:center;justify-content:center;padding:48px 28px}.authx-wrap{width:100%;max-width:430px}.authx-eyebrow{font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:#0E4C8F}.authx h1{font:700 34px var(--font-heading,Georgia,serif);color:#002B54;letter-spacing:-.02em;margin:8px 0}.authx-desc{color:#687587;font-size:14px;line-height:1.6}.authx-card{background:#fff;border:1px solid #DDE3EA;border-radius:16px;padding:30px;box-shadow:0 20px 55px rgba(0,43,84,.08);margin-top:22px}.authx-label{display:block;font-size:13px;font-weight:700;color:#002B54;margin:0 0 6px}.authx-field{width:100%;box-sizing:border-box;padding:12px 14px;border:1.5px solid #DDE3EA;border-radius:9px;font-size:16px;outline:none;background:#fff}.authx-field:focus{border-color:#0E4C8F;box-shadow:0 0 0 3px rgba(14,76,143,.12)}.authx-fields{display:grid;gap:15px}.authx-btn{width:100%;margin-top:22px;min-height:46px;border:0;border-radius:9px;background:#FAB72D;color:#002B54;font-size:14px;font-weight:800;cursor:pointer}.authx-btn:disabled{opacity:.65}.authx-error{margin-top:14px;padding:11px 13px;border-radius:8px;background:#FBEAEA;color:#A42C27;font-size:13px}.authx-foot{text-align:center;margin-top:18px;color:#687587;font-size:13px}.authx-foot a{color:#0E4C8F;font-weight:800;text-decoration:none}.authx-note{margin-top:14px;font-size:11px;color:#7A8699;line-height:1.55}
    @media(max-width:900px){.authx{grid-template-columns:1fr}.authx-story{display:none}.authx-main{min-height:100vh;padding:36px 20px}}
  `}</style><aside className="authx-story"><div><Link to="/" className="authx-brand">LexAMS</Link><div style={{marginTop:70}}><div className="authx-kicker">Programme operations, connected</div><h2>From registration to results in one workspace.</h2><p>Manage participants, attendance, assessments, surveys, certificates and reporting without rebuilding the same information across spreadsheets and forms.</p><div className="authx-points"><div className="authx-point">Free workspace includes up to 50 participants</div><div className="authx-point">Secure email-link authentication</div><div className="authx-point">Built for training providers, NGOs and institutions</div></div></div></div><div className="authx-meta">LexAMS · A LexoGraphix Plus product · Banjul, The Gambia, West Africa</div></aside><main className="authx-main"><div className="authx-wrap"><Link to="/" style={{font:'700 23px var(--font-heading,Georgia,serif)',color:'#002B54',textDecoration:'none'}}>LexAMS</Link><div style={{marginTop:28}} className="authx-eyebrow">{eyebrow}</div><h1>{title}</h1><p className="authx-desc">{description}</p><div className="authx-card">{children}</div>{footer&&<div className="authx-foot">{footer}</div>}</div></main></div>
}
