import { Link, NavLink } from 'react-router-dom';

const links=[['/features','Features'],['/pricing','Pricing'],['/solutions','Solutions'],['/security','Security']];
export default function MarketingLayout({children}){
 return <div className="mk-site"><style>{`
 .mk-site{--navy:#002B54;--navy2:#0E4C8F;--gold:#FAB72D;--paper:#FBFAF7;--ink:#122033;--muted:#687587;--line:#DDE3EA;min-height:100vh;background:var(--paper);color:var(--ink);font-family:var(--font-body,Inter,sans-serif)}
 .mk-container{width:min(1180px,calc(100% - 48px));margin:auto}.mk-nav{position:sticky;top:0;z-index:50;background:rgba(251,250,247,.94);backdrop-filter:blur(16px);border-bottom:1px solid var(--line)}.mk-nav-in{height:72px;display:flex;align-items:center;justify-content:space-between;gap:24px}.mk-brand{font:700 25px var(--font-heading,Georgia,serif);color:var(--navy);text-decoration:none}.mk-links{display:flex;align-items:center;gap:24px}.mk-links a{font-size:13px;font-weight:700;color:#526174;text-decoration:none}.mk-links a.active{color:var(--navy)}.mk-actions{display:flex;gap:10px}.mk-btn{display:inline-flex;min-height:44px;align-items:center;justify-content:center;padding:0 18px;border-radius:9px;text-decoration:none;font-size:13px;font-weight:800}.mk-btn.primary{background:var(--navy);color:#fff}.mk-btn.gold{background:var(--gold);color:var(--navy)}.mk-btn.ghost{border:1px solid var(--line);color:var(--navy);background:#fff}
 .mk-hero{padding:92px 0 76px;background:radial-gradient(circle at 85% 15%,rgba(250,183,45,.18),transparent 28%),linear-gradient(180deg,#FBFAF7,#F4F1E9)}.mk-hero-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:68px;align-items:center}.mk-kicker{font-size:11px;font-weight:900;letter-spacing:.14em;text-transform:uppercase;color:var(--navy2)}.mk-hero h1,.mk-page-hero h1{font:700 clamp(42px,5vw,70px)/1.02 var(--font-heading,Georgia,serif);letter-spacing:-.035em;color:var(--navy);margin:12px 0 0}.mk-hero p,.mk-page-hero p{font-size:18px;line-height:1.75;color:var(--muted);max-width:700px}.mk-hero-actions{display:flex;gap:12px;margin-top:28px;flex-wrap:wrap}.mk-product{border:1px solid var(--line);background:#fff;border-radius:22px;padding:20px;box-shadow:0 28px 70px rgba(0,43,84,.12)}.mk-product img{width:100%;display:block;border-radius:12px}.mk-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.mk-metric{border:1px solid var(--line);border-radius:12px;padding:14px;background:#fff}.mk-metric strong{display:block;color:var(--navy);font-size:18px}.mk-metric span{font-size:11px;color:var(--muted)}
 .mk-section{padding:92px 0}.mk-alt{background:#F4F1E9;border-block:1px solid var(--line)}.mk-section-head{display:grid;grid-template-columns:.72fr 1.28fr;gap:70px;margin-bottom:40px;align-items:end}.mk-section h2{font:700 clamp(32px,4vw,50px)/1.08 var(--font-heading,Georgia,serif);letter-spacing:-.025em;color:var(--navy);margin:8px 0}.mk-lede{font-size:16px;line-height:1.75;color:var(--muted)}.mk-grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.mk-card{border:1px solid var(--line);background:#fff;border-radius:16px;padding:26px}.mk-card h3{font:700 20px var(--font-heading,Georgia,serif);color:var(--navy);margin:0 0 10px}.mk-card p{font-size:13px;line-height:1.7;color:var(--muted);margin:0}.mk-list{display:grid;gap:12px;padding:0;list-style:none}.mk-list li{display:flex;gap:10px;color:#44556A;font-size:14px}.mk-list li:before{content:'✓';font-weight:900;color:var(--navy2)}
 .mk-page-hero{padding:80px 0 54px;background:linear-gradient(180deg,#FBFAF7,#F5F2EA)}.mk-page-hero h1{font-size:clamp(40px,5vw,62px)}.mk-pricing{display:grid;grid-template-columns:1fr 1.08fr;gap:22px}.mk-price{border:1px solid var(--line);background:#fff;border-radius:18px;padding:30px}.mk-price.pro{border:2px solid var(--gold);box-shadow:0 20px 45px rgba(0,43,84,.1)}.mk-price-num{font:700 38px var(--font-heading,Georgia,serif);color:var(--navy)}.mk-table{width:100%;border-collapse:collapse;background:#fff;border:1px solid var(--line);border-radius:14px;overflow:hidden}.mk-table th,.mk-table td{padding:14px 16px;border-bottom:1px solid var(--line);text-align:left;font-size:13px}.mk-table th{background:#EEF3F8;color:var(--navy)}
 .mk-faq{display:grid;gap:12px}.mk-faq details{background:#fff;border:1px solid var(--line);border-radius:12px;padding:18px 20px}.mk-faq summary{cursor:pointer;font-weight:800;color:var(--navy)}.mk-faq p{color:var(--muted);line-height:1.65;font-size:14px}.mk-cta{padding:72px 0;background:var(--navy);color:#fff}.mk-cta-in{display:flex;align-items:center;justify-content:space-between;gap:36px}.mk-cta h2{font:700 clamp(30px,4vw,48px) var(--font-heading,Georgia,serif);margin:0}.mk-footer{background:#001C37;color:rgba(255,255,255,.72);padding:42px 0}.mk-footer-grid{display:grid;grid-template-columns:1.5fr repeat(3,1fr);gap:32px}.mk-footer h4{color:#fff;margin:0 0 12px}.mk-footer a{display:block;color:rgba(255,255,255,.72);text-decoration:none;font-size:12px;margin:8px 0}.mk-foot-brand{font:700 24px var(--font-heading,Georgia,serif);color:#fff}
 @media(max-width:900px){.mk-links{display:none}.mk-hero-grid,.mk-section-head,.mk-grid3,.mk-footer-grid{grid-template-columns:1fr}.mk-pricing{grid-template-columns:1fr}.mk-cta-in{align-items:flex-start;flex-direction:column}}@media(max-width:620px){.mk-container{width:min(100% - 32px,1180px)}.mk-nav-in{height:64px}.mk-actions .ghost{display:none}.mk-hero{padding:64px 0 52px}.mk-hero h1{font-size:42px}.mk-hero p{font-size:16px}.mk-hero-actions{flex-direction:column}.mk-hero-actions .mk-btn{width:100%}.mk-metrics{grid-template-columns:1fr}}
 `}</style><header className="mk-nav"><div className="mk-container mk-nav-in"><Link className="mk-brand" to="/">LexAMS</Link><nav className="mk-links">{links.map(([to,label])=><NavLink key={to} to={to}>{label}</NavLink>)}</nav><div className="mk-actions"><Link className="mk-btn ghost" to="/login">Sign in</Link><Link className="mk-btn primary" to="/signup">Start free</Link></div></div></header><main>{children}</main><footer className="mk-footer"><div className="mk-container mk-footer-grid"><div><div className="mk-foot-brand">LexAMS</div><p style={{fontSize:12,lineHeight:1.7}}>Activity and programme management for training providers, NGOs and institutions.</p><p style={{fontSize:11}}>A LexoGraphix Plus product · Banjul, The Gambia, West Africa</p></div><div><h4>Product</h4><Link to="/features">Features</Link><Link to="/pricing">Pricing</Link><Link to="/security">Security</Link></div><div><h4>Solutions</h4><Link to="/solutions/training-providers">Training providers</Link><Link to="/solutions/ngos">NGOs</Link><Link to="/solutions/education">Education</Link></div><div><h4>Company</h4><Link to="/about">About</Link><Link to="/contact">Contact</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></div></div></footer></div>
}
