import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import PublicExperienceLayout, { PublicCard, PublicNotice } from '../../components/PublicExperienceLayout';
import { publicApi } from '../../lib/publicApi';
import useDocumentTitle from '../../lib/useDocumentTitle';

export default function SurveyPublic(){
  useDocumentTitle('Survey');
 const {token}=useParams(); const [survey,setSurvey]=useState(null); const [questions,setQuestions]=useState([]); const [answers,setAnswers]=useState({}); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [submitted,setSubmitted]=useState(false); const [sending,setSending]=useState(false);
 useEffect(()=>{publicApi('survey',token).then(b=>{setSurvey(b.survey);setQuestions(b.questions)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[token]);
 async function submit(e){e.preventDefault();setSending(true);setError('');try{await publicApi('survey',token,{method:'POST',body:JSON.stringify({name,email,answers})});setSubmitted(true)}catch(e){setError(e.message)}finally{setSending(false)}}
 if(loading)return <PublicExperienceLayout eyebrow="Survey" title="Loading survey…"/>; if(!survey)return <PublicExperienceLayout eyebrow="Survey" title="Survey unavailable"><PublicNotice tone="error">{error}</PublicNotice></PublicExperienceLayout>;
 if(submitted)return <PublicExperienceLayout eyebrow="Survey complete" title="Thank you" organizationName={survey.organization_name} organizationLogo={survey.organization_logo} narrow><PublicCard><div style={{textAlign:'center'}}><div style={{fontSize:38}}>✓</div><h3>Response recorded</h3><p style={{color:'#687587'}}>Thank you for sharing your feedback.</p></div></PublicCard></PublicExperienceLayout>;
 const answered=questions.filter(q=>String(answers[q.id]??'').trim()).length;
 return <PublicExperienceLayout eyebrow="Feedback survey" title={survey.title} description={survey.description} organizationName={survey.organization_name} organizationLogo={survey.organization_logo}><div className="lex-public-progress"><span style={{width:`${questions.length?answered/questions.length*100:0}%`}}/></div>{survey.allow_anonymous&&<PublicNotice>This survey is anonymous.</PublicNotice>}<form onSubmit={submit} style={{marginTop:16}}>{!survey.allow_anonymous&&<PublicCard><div className="lex-public-grid2"><div><label className="lex-public-label">Your name</label><input className="lex-public-input" value={name} onChange={e=>setName(e.target.value)}/></div><div><label className="lex-public-label">Email</label><input className="lex-public-input" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></div></div></PublicCard>}{questions.map((q,i)=><PublicCard key={q.id}><div style={{fontWeight:700,color:'#002B54'}}>{i+1}. {q.question_text}{q.required&&<span style={{color:'#B9342A'}}> *</span>}</div><div style={{marginTop:14}}>{q.question_type==='rating'&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{[1,2,3,4,5].map(v=><button type="button" className={`lex-public-button ${answers[q.id]===String(v)?'secondary':'ghost'}`} key={v} onClick={()=>setAnswers({...answers,[q.id]:String(v)})}>{v}</button>)}</div>}{q.question_type==='multiple_choice'&&(q.options||[]).map(opt=><label key={opt} style={{display:'block',padding:'10px 0'}}><input type="radio" name={q.id} checked={answers[q.id]===opt} onChange={()=>setAnswers({...answers,[q.id]:opt})}/> {opt}</label>)}{q.question_type==='yes_no'&&<div style={{display:'flex',gap:10}}>{['Yes','No'].map(v=><button type="button" key={v} className={`lex-public-button ${answers[q.id]===v?'secondary':'ghost'}`} onClick={()=>setAnswers({...answers,[q.id]:v})}>{v}</button>)}</div>}{q.question_type==='text'&&<textarea className="lex-public-textarea" rows="4" value={answers[q.id]||''} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}/>}</div></PublicCard>)}{error&&<PublicNotice tone="error">{error}</PublicNotice>}<div className="lex-public-actions"><button className="lex-public-button secondary" disabled={sending}>{sending?'Submitting…':'Submit response'}</button></div></form></PublicExperienceLayout>
}
